name: Create model-service Pre-release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-*'

jobs:
  build_and_publish:
    name: Build & Create GitHub Pre-release
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout code at the tagged commit
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push Docker image
        run: |
          REPO=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2 | tr '[:upper:]' '[:lower:]')
          IMG_TAG="ghcr.io/${REPO}/${NAME}:${{ github.ref_name }}"
          
          BASE_TAG=${IMG_TAG#v} # without the v in front
          
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t "${BASE_TAG}" \
            --push .

      - name: Create GitHub Pre-release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Pre-release ${{ github.ref_name }} (model-service)
          body: "Automated pre-release of the model-service."
          prerelease: true
          draft: false
